### ISSUE TITLE
Sass variables and media queries incorrectly interpreted as CSS properties

### ISSUE THREAD

**Issue by rafistrauss** [kisstkondoros/csstriggers#5]
For example, in the following mixin declaration:

`@mixin object-fit($fit: fill, $position: null) {`
the variable `$position` is interpreted as a CSS propery

![image](https://user-images.githubusercontent.com/4576234/43170412-05a48250-8f73-11e8-8123-4a9ff9611f3a.png)

A similar thing happens in media queries:

![image](https://user-images.githubusercontent.com/4576234/43170474-4cc096ba-8f73-11e8-99a4-39bf8676f41f.png)

**Comment by kisstkondoros** [comment]
Thanks for reporting it, I'll look into this!
(The scanning is rather dumb in this regard, since it knows nothing actually about css, scss, etc at all. it just searches for the keywords)

**Comment by kisstkondoros** [comment]
Version 0.7.0 was just released and is available in the market, which contains a partial fix for this.

I've added some minor improvements to avoid cases like this, but without a proper ast parser it is not going to work perfectly...
I've also investigated a bit the vscode language server implementation for css scss and less, that might be reusable as a dependency (since I would need to access the internals of it - especially the parsers)
but since the extension is not limited to these, I would need to get a proper one for stylus as well (stylable would be just fine with the css parser IMO)

I'm going to close this issue, but feel free to file a new issue if you encounter some other case like this!
