### ISSUE TITLE
Browser differences not reflected and sub sequence changes

### ISSUE THREAD

**Issue by Hammster** [kisstkondoros/csstriggers#7]
While the data in [csstriggers.ts](csstriggers/src/server/csstriggers.ts) contain all browser the display is currently only showing the results for blink (Chrome) it would be nice to see the actual distinct browser support.

Also seeing the different behaviours for initial values besides the sub sequence changes are helpful for certain tasks, even though a little neglect able for animations.

For example for `opacity` is a tricky property since it differs strongly between browser engines. It is the to go property for FLIP but that does `painting` in edge. And webkit needs the full procedure for anything but windows and cursors.

**Comment by kisstkondoros** [comment]
Yes indeed, my initial thought was to show how a certain css property affects the performance in the form of an indicator on the gutter, and for that I had to pick a browser, and my choice was blink.

I would maybe implement the followings:
1. a configuration property could be added, which would default to 'blink' so that it would be a non breaking change for the current users.
2. the detailed information in the hover widget (markdown) would also contain the information for other browsers / engines, perhaps also in a configurable way (e.g. default would be to show it for all browsers / engines but you could opt out from showing them one by one)

PR is welcomed for this ;)

**Comment by kisstkondoros** [comment]
Version 0.10.0 was just released, please refer to the readme for the new configuration properties.
